### ISSUE TITLE
Game crashes on continuing

### ISSUE THREAD

**Issue by GandWuser** [Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest#2]
**What part of the game is impacted?**
Continue screen

**What operating system and hardware setup are you using?**
 - System Manufacturer: MSI
 - Processor: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
 - RAM: 32GB
 - OS: Windows 10
 - Graphics Card: Geforce 3080 laptop version
 - Sound Card: realtek probably???

**Description**
Pressing A on the continue screen and after pausing and resuming on the continue screen crashes the game. 

**To Reproduce**
Get to the continue screen and press A on the controller

**Expected behavior**
Not crashing

**Actual result**
Game Maker error screen about missing sprites

**Screenshots**
[meijinka continue  crash](https://github.com/Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest/assets/11055031/2f5a6034-f79f-4096-aa3b-50b34e481b4b)

**Additional context**
N/A

**Comment by Drillimation** [comment]
There appeared to be an issue with the Step event in the Control object when the arcade machine is powered on. We have created a failsafe for this problem, and the game can only be paused when the game says the second player can join. We're also working on improving the performance.

**Comment by Drillimation** [comment]
Problem has been possibly remedied in the 1.0.1 update.
