### ISSUE TITLE
Typo in St3

### ISSUE THREAD

**Issue by AverageCheetosFan** [Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest#3]
**What part of the game is impacted?**
Stage 3 dialogue

**What operating system and hardware setup are you using?**
 - System Manufacturer: GPD
 - Processor: Intel Celeron N4100 CPU @ 1.10 GHz  1.10 GHz
 - RAM: 8.00 GB
 - OS: Windows 10 Pro
 - Graphics Card: I've got
 - Sound Card: no idea

**Description**
The last line found in Marisa's Stage 3 dialogue has a typo in it.

**To Reproduce**
Get to the Stage 3 boss with Marisa as the first player.

**Expected behavior**
Emiri's last line of dialogue should have an apostrophe in the word "you're."

**Actual result**
The word is displayed with a question mark in the middle - "you?re."

**Screenshots**
![bigs_f](https://github.com/Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest/assets/89362010/fa0b9efa-4aca-47d1-bc41-f5330f0bbff8)

**Comment by Drillimation** [comment]
The error was found in "stage_3_marisa_prebattle_en.json". We have since corrected the bug and will be released in a future update for the game.
