### ISSUE TITLE
Unused right moving sprites

### ISSUE THREAD

**Issue by AverageCheetosFan** [Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest#5]
**What part of the game is impacted?**
All moving bosses

**What operating system and hardware setup are you using?**
 - System Manufacturer: Intel
 - Processor: Intel Core i7-6500U CPU @ 2.50GHz   2.59 GHz
 - RAM: 8.00 GB
 - OS: Windows 10 IoT Enterprise LTSC
 - Graphics Card: Still got
 - Sound Card: no idea

**Description**
All bosses use only one set of sprites for moving.

**To Reproduce**
Get to any boss phase in which the boss moves. (Spell Cards or otherwise)

**Expected behavior**
Bosses should use their left set of sprites when they move to the left, and the right set for moving to the right.

**Actual result**
Bosses always use their left set of sprites regardless of what direction they're moving in, leaving the right set unused.

**Screenshots**
https://github.com/Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest/assets/89362010/7356c928-978d-413e-a051-eea647792001

**Comment by Drillimation** [comment]
This has been a known issue for some time, even in the first reveal trailer. We're still trying to figure out on how to fix it.

**Comment by Drillimation** [comment]
We have fixed this issue, and will be put out when the game officially releases.
