### ISSUE TITLE
Free Play sprite inconsistency

### ISSUE THREAD

**Issue by AverageCheetosFan** [Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest#6]
**What part of the game is impacted?**
Free Play stage select

**What operating system and hardware setup are you using?**
 - System Manufacturer: Intel
 - Processor: Intel Core i7-6500U CPU @ 2.50GHz   2.59 GHz
 - RAM: 8.00 GB
 - OS: Windows 10 IoT Enterprise LTSC
 - Graphics Card: Still got
 - Sound Card: no idea

**Description**
One of the bosses' sprites in the Free Play menu is different from their ingame sprite.

**To Reproduce**
Use the Free Play menu.

**Expected behavior**
Kagami should be displayed wearing white socks.

**Actual result**
Kagami's socks are missing, unlike during her boss fight.

**Screenshots**
![Touhou_Meijinka_~_Song_of_Divine_Tempest_GYND4n6hnm](https://github.com/Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest/assets/89362010/82e2fffc-b6c3-4800-b927-62e9fc07e894)
![Touhou_Meijinka_~_Song_of_Divine_Tempest_AnGdbBxL2s](https://github.com/Drillimation/Touhou-Meijinka-Song-of-Divine-Tempest/assets/89362010/06bb1df3-8a2e-4c6e-9dfe-0e335242063f)

**Comment by Drillimation** [comment]
This isn't a bug impacting the game, but rather a graphical issue that we are trying to address.
